branch-defaults:
  master:
    environment: staging
    group_suffix: null
global:
  application_name: direct-linking-backend
  branch: null
  default_ec2_keyname: worldbrain-dev
  default_platform: Node.js
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
